
export enum CourseCategory{
    IT = "IT",
    PROGRAMMING = "Programming",
    SCIENCE = "Science",
    LIFESTYLE = "Life",
    SPORTS = "Sports",
    FINANCE = "Finance",
    EDUCATION = "Education",
    BUSINESS = "Business",
    TECHNOLOGY= "Technology",
    LANGUAGES = "Languages",
    MUSIC = "Music",
    FASHION= "Fashion",
    SOFTWAREDEVELOPMENT = "Fashion and Style",
    ARTIFICALINTELLIGENCE = "Artificial Intelligence",
    HEALTH = "Health",
    ARTS = "Arts",
    ARTSANDDESIGN = "Arts and Design",
    TRAVEL = "Travel",
    CULTURE = "Culture",
    GAMING = "Gaming",
    ENVIRONMENT = "Environment", 
}